"""
Data Schemas for TriageIQ SOC Alert Pipeline
"""

from typing import List, Dict, Any, Optional, TypedDict
from pydantic import BaseModel, Field
from datetime import datetime


class SOCAlert(BaseModel):
    """Normalized Security Operations Center (SOC) Alert object."""
    alert_id: str = Field(..., description="Unique alert identifier")
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    source_ip: str = Field(..., description="Source IP address triggering alert")
    destination_ip: str = Field(..., description="Target / Destination IP address")
    destination_port: Optional[int] = Field(default=80, description="Target port")
    protocol: Optional[str] = Field(default="TCP", description="Network protocol")
    event_type: str = Field(..., description="Category or signature name of event")
    raw_severity: str = Field(default="MEDIUM", description="Original raw severity")
    user: Optional[str] = Field(default="SYSTEM", description="Target or associated user")
    hostname: Optional[str] = Field(default="workstation-01", description="Affected host name")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Raw event payload metadata")
    iocs: List[str] = Field(default_factory=list, description="Extracted Indicators of Compromise (IPs, hashes, domains)")


class ThreatIntel(BaseModel):
    """Enrichment metadata fetched from Threat Intel sources (VirusTotal, AbuseIPDB)."""
    ioc: str
    ioc_type: str  # "ip", "domain", "hash"
    reputation_score: int = Field(default=0, description="Risk score from 0 (clean) to 100 (critical threat)")
    malicious_votes: int = 0
    benign_votes: int = 0
    threat_tags: List[str] = Field(default_factory=list)
    source_api: str = "Mock/Cache"  # "VirusTotal", "AbuseIPDB", "Simulated"
    details: str = ""


class CorrelatedGroup(BaseModel):
    """Group of temporally or asset-correlated alerts representing an attack campaign."""
    campaign_id: str
    alert_ids: List[str]
    primary_ip: str
    target_asset: str
    attack_stage: str  # e.g., "Reconnaissance", "Initial Access", "Credential Access", "Exfiltration"
    risk_score: float = Field(default=0.0, description="Composite campaign risk score")
    summary: str


class TriageDecision(BaseModel):
    """AI Triage outcome for a specific alert or correlated alert campaign."""
    alert_id: str
    action: str = Field(..., description="AUTO_DISMISS | ESCALATE | NEEDS_HUMAN_REVIEW")
    calculated_severity: str = Field(..., description="CRITICAL | HIGH | MEDIUM | LOW | FALSE_POSITIVE")
    confidence_score: float = Field(default=0.9, description="Confidence rating between 0.0 and 1.0")
    reasoning: str = Field(..., description="Explanation for the decision")
    mitre_tactics: List[str] = Field(default_factory=list, description="Associated MITRE ATT&CK tactics")


class IncidentReport(BaseModel):
    """Structured markdown incident report generated by the Reporting Agent."""
    incident_id: str
    title: str
    timestamp: str
    severity: str
    summary: str
    affected_assets: List[str]
    mitre_tactics: List[str]
    timeline: List[Dict[str, str]]
    evidence: List[str]
    recommended_actions: List[str]
    markdown_body: str


class TriageState(TypedDict):
    """LangGraph State Container for multi-agent pipeline."""
    raw_alerts: List[Dict[str, Any]]
    alerts: List[SOCAlert]
    threat_intel: Dict[str, ThreatIntel]
    correlations: List[CorrelatedGroup]
    triage_decisions: Dict[str, TriageDecision]
    incident_reports: List[IncidentReport]
    trace_logs: List[Dict[str, Any]]
    current_step: str
    noise_reduced_percent: float
